FROM openjdk:17-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the application jar file to the container
COPY target/e-learning-0.0.1-SNAPSHOT.jar .

# Expose port 8080
EXPOSE 8080

# Start the application
CMD ["java", "-jar", "e-learning-0.0.1-SNAPSHOT.jar"]